# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Jana": "00_core.ipynb",
         "hello": "00_core.ipynb",
         "lang": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jana-rajova.github.io/nbdevtest/"

git_url = "https://github.com/jana-rajova/nbdevtest/tree/master/"

def custom_doc_links(name): return None
