# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jana-rajova.github.io/nbdev_test/"

git_url = "https://github.com/jana-rajova/nbdev_test/tree/master/"

def custom_doc_links(name): return None
