# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Jana']

# Cell
class Jana:
    """
    Creade class Jana with the attribute person
    """
    attr1 = "person"
    count = 1

    def replicate(self, times=1):
        Jana.count *= 2**times
        print("There are now ", Jana.count)
    def restart(self):
        Jana.count = 1
        print("We're back to", Jana.count, Jana.attr1)