# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['hello']

# Cell
def hello(name):
    "Say hii"
    assert type(name) == str
    print("Hello", name)
